apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: blu-live-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        # We check both DNS and the Port
        command: ['sh', '-c', "until nslookup mongodb && nc -zvw1 mongodb 27017; do echo waiting for mongodb; sleep 2; done"]
      containers:
      - name: backend
        image: docker.io/jonahirande/blu-live-clinic-backend:latest
        imagePullPolicy: Always # Forces OpenShift to pull your new code
        env:
        - name: MONGO_URI
          value: "mongodb://clinic_admin:p%40ssw0rd_db_user@mongodb:27017/liveclinic?authSource=liveclinic"
        ports:
        - containerPort: 5000
        # This keeps the pod from crashing immediately if there's a minor delay
        livenessProbe:
          httpGet:
            path: /api/patients
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20