apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: live-clinic-url
  namespace: blu-live-clinic
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 80
  tls:
    termination: edge
    # This automatically redirects http traffic to https
    insecureEdgeTerminationPolicy: Redirect
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDDDCCAfSgAwIBAgIUSO7bU/OwvgY1DYeZ4zjHgr8UVzMwDQYJKoZIhvcNAQEL
      BQAwGzEZMBcGA1UEAwwQQmx1RGl2ZS1Mb2NhbC1DQTAeFw0yNjAyMjAxNzQ5MTRa
      Fw0yNzAyMjAxNzQ5MTRaMCExHzAdBgNVBAMMFiouYXBwcy5sYWIub2NwLmJsdWRp
      dmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCYxSDI+t1TGZ9z7Chg
      abUsS1I8OO5HqRaeA8e6rxw8ZIK9NxDDO3UdYyLfHhWe5/sWXmzdaj9foP/itdC+
      KW3K8kJxiTJjroPv7jvwCGNyShU+5qTNE0280pmOm3DmptWYLv4690b978hO/Z5B
      BwUtvOFOLt1j3eIqybiIy66QAKb6rwA16EaZINIfnqvyXCqPBBz7gjrgOoYem/AK
      20X7u2AXtv1g6t0/+oj/qgl8NW6cfg+3AFRnB9Iaw0h3YLF5i2XS8Ky+KnMx5oW2
      qWn9KSeC+bCEqbmI1wP7SMVbhwDLIDGnDyZjJB3C/+JYT3Te5pFgiBtFDyfcoIjZ
      pRzBAgMBAAGjQjBAMB0GA1UdDgQWBBSVo0qEA+kp1gxezL1HjWZ0DLpDkDAfBgNV
      HSMEGDAWgBQLgyMIV4QahdR+a4Y954TSFP9NKDANBgkqhkiG9w0BAQsFAAOCAQEA
      FWvsMdkPJYA+wF4xd81AEtXsTKczko0x4sx78F/XkZvB/4cEbaQJOw4UcnPRm3Nv
      39APhyOiwodqYZoKMxFnMvBK+DByQmYJIf7FuHu02VQnWx1us1oMzK8fdLVZ67Ju
      oNP5ryBUnJIgSVq8S5gWbq/zQw6HAPdwnpr0iLSXVF5vMVI65fmeDnUx7AOJo1Zv
      LBJy1uJpnfey2v6EyejUgn1UlqzorGcYYOLs9/V4KMcX1t9GvfHGW46JdTS+3QSC
      zeryyhHXRYKLXHjT+wXXFFYVD2CCGfOpxqHyIXw2JZ/6iPDZZMKJ0x8CQE1WlIEW
      PcaeAbz36BHae931gdeVyg==
      -----END CERTIFICATE-----  
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCYxSDI+t1TGZ9z
      7ChgabUsS1I8OO5HqRaeA8e6rxw8ZIK9NxDDO3UdYyLfHhWe5/sWXmzdaj9foP/i
      tdC+KW3K8kJxiTJjroPv7jvwCGNyShU+5qTNE0280pmOm3DmptWYLv4690b978hO
      /Z5BBwUtvOFOLt1j3eIqybiIy66QAKb6rwA16EaZINIfnqvyXCqPBBz7gjrgOoYe
      m/AK20X7u2AXtv1g6t0/+oj/qgl8NW6cfg+3AFRnB9Iaw0h3YLF5i2XS8Ky+KnMx
      5oW2qWn9KSeC+bCEqbmI1wP7SMVbhwDLIDGnDyZjJB3C/+JYT3Te5pFgiBtFDyfc
      oIjZpRzBAgMBAAECggEAOpynD3TwJUnXW2pns1XbJLthOam+AdBl1QouPvmgI6uM
      XXwa+kx9imDWqDOqp+To+JQRwIFa/x2ODzUieVL7xLldtKGmq4fxJsSISndtcBPs
      Qs3KvMODN8a1E3mfv16S5GhjMcxdeF/ewi+b3+cJnZqx9oUUe5RNiY0LN7CtsKF3
      SV/fIxJa9+d2SZxksaXBzvOP4F1INU0MPSj48ul7AeXxStwkW/+fRGk1qwXHlE03
      3EghYtDGK1A4/7rdrEj49YciiJmsHCd6shLnce/tfzoduFS+8cgFAJwdZpLOAuvm
      mYNmh/zE/ITShJPp7prP8VSXN9NqjScSDCCCUCR64QKBgQDUoOmt2ZlVenfQhh6n
      7iMbvbZJQBiFywkW+9q5BmVCkfsUly4QAKPOBR1zA+O3Pi2TUR57U9mFKDPrdFu4
      35P+Fi/gAsM9jKq8AVGxVLvk7xZW/8cFQFUHTE5BaEPEmP2Y4WFbkEg5hbtqB+fm
      hMJFQVr63jaKmr+oIPF8cKT5pwKBgQC37oIzdfM/iK83BTtziurpTWFjIIW4ejhX
      fhbrosbVcL8Kail5jTKp3TC29/4riC79+iq95bH/v54uU8Ym2xeAK7nCvboNT8MW
      Tvyp+pK1M3afdERuw5FO3Cqfhedjvu71qfL24RE9PmYGJRPDb86v8JQ3VFqAH/2R
      S0FueGgzVwKBgF5vVTnMYgiPyvUHDEiDQH6KpJIl8H5DrbbShtMUXxbQ5RXBC0k6
      L4ZJyUmS2alB6VX7ejFGDV7RezXAyRfz3LPFwN+Z+oK0ngPABjtfKdBEy8Q593eC
      mgESx9LO7wI6/K7Qsr/K9fjuR02RU1KTdgDyROkUll662hJfB0HAedUTAoGACmSA
      mNXGS8W2WL6D8HBd+5aytP4mcBj/y/nE48WLxI2dTcJX25Vd0nk8Amqawuzr8s/K
      0HYFC7VRA78aCCIC/uv5kAZWV+A03rLR1ezhkzl4L2RLZZLJSBJqmh7fxyQHrnvO
      zaJD7hjzfM9lgXp0zD4kscejYW/tTONarBpDkPsCgYAxGqBGX9/TSWsaLtDbJvB5
      xRSYfo5N2hkaAavzGboYuoHVfadjFwg29LjKl48pPmhJb/3l2vJP3vt//jwg+kx4
      R5EfUsNY+tySKpV1/dEdXE0b+i0JuzkRccnkvLcjwPFaDIaI0j1x4GQxmXbcHCY9
      6AA5iDOxZq6ASLttAVoyEw==
      -----END PRIVATE KEY-----
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIDFzCCAf+gAwIBAgIUGFGXZn6FHZB9nFYBPXdS8GYwGL4wDQYJKoZIhvcNAQEL
      BQAwGzEZMBcGA1UEAwwQQmx1RGl2ZS1Mb2NhbC1DQTAeFw0yNjAyMjAxNzQ3NDla
      Fw0yODEyMTAxNzQ3NDlaMBsxGTAXBgNVBAMMEEJsdURpdmUtTG9jYWwtQ0EwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZo5mZCYChtApfnL6VHkgbg7nh
      wLD/YnXdikfgKSgg5/qyWCS4aATkiDbkNPlIPOFGR5AenEMVGZ3D9wvcsGDtkqmk
      BQpW8Qkq/F0Wq7mCGLq0350PakeHX942UniDyEP9Gh+AgsSLKVQshe8Tv+nd/dj1
      SBk2R7YKuQqiund34T6yE8eHD4ulHAkXuukstCTej7M8nJSxUOrkkVA4Kw8kSBqA
      /iKc07IZ9hfNK3h21A+OFbfHMm0bUzzAn1oInhzOhXjuWYtyF8Shgkunsc0oxpcI
      ZOvx/uB7u74NjQIHHPWqIXxK7V80QdjoTh+sV11otDktqmjaO/x82pDtSO11AgMB
      AAGjUzBRMB0GA1UdDgQWBBQLgyMIV4QahdR+a4Y954TSFP9NKDAfBgNVHSMEGDAW
      gBQLgyMIV4QahdR+a4Y954TSFP9NKDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
      DQEBCwUAA4IBAQBMhaSwgc9zIoh5vM/EDCfFLjvO4m7gUM2dIBtwMCy/hkGUMfsP
      xZ1X+RJ2OLananyc/BZFw9+i7zTRWZfFFdhLhGJ+ODIn9UcH5IEg2slNMAPrxwaT
      0BvhQi3skQiikhyu89UJYnV/iIPr5ZpLwWiDiyyRUyVcXQ9RnM/cJzFZq/G6+/EA
      5p07dRXGukAIiRmbCSoisYOYVlVGPvuFkyFZnTEHSJYH25GaRcDufAdYLFfD4GjX
      rwg7CTnb67o4QWegrDUEKpkju9dsEXgE8VwGo+cENIqKVXwZvK7X1wnaYXe3Lgil
      biw2zrTvaVbwmGFaP/nXAKRdg7ZFpmMtjNB6
      -----END CERTIFICATE-----  