apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: blu-live-clinic
  name: mongodb-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-anyuid-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: mongodb-sa